version: "3"
services:
      node9:
          build:
              context: .
              dockerfile: docker/Dockerfile-node-9-alpine
          user: "node"
          environment:
            - NODE_ENV=production
          volumes:
            - .:/app
          ports:
            - "8089:3000"
          command: "npm start"
      node8:
          build:
              context: .
              dockerfile: docker/Dockerfile-node-8-alpine
          user: "node"
          environment:
            - NODE_ENV=production
          volumes:
            - .:/app
          ports:
            - "8088:3000"
          command: "npm start"
      node7:
          build:
              context: .
              dockerfile: docker/Dockerfile-node-7-alpine
          user: "node"
          environment:
            - NODE_ENV=production
          volumes:
            - .:/app
          ports:
            - "8087:3000"
          command: "npm start"
      node6:
          build:
              context: .
              dockerfile: docker/Dockerfile-node-6-alpine
          user: "node"
          environment:
            - NODE_ENV=production
          volumes:
            - .:/app
          ports:
            - "8086:3000"
          command: "npm start"
      test-node6:
          build:
              context: .
              dockerfile: docker/Dockerfile-node-6-alpine
      test-node7:
          build:
              context: .
              dockerfile: docker/Dockerfile-node-7-alpine
      test-node8:
          build:
              context: .
              dockerfile: docker/Dockerfile-node-8-alpine
      test-node9:
          build:
              context: .
              dockerfile: docker/Dockerfile-node-9-alpine
